### ISSUE TITLE
checksum error at yarn install

### ISSUE THREAD

**Issue by pimperator** [sindresorhus/ansi-escapes#13]
Hi Guys,

since yesterday afternoon  (about 22 hours) I keep recieving  the error message at 'yarn install' shown below.

```
verbose 11.853500195 Error: https://registry.yarnpkg.com/ansi-escapes/-/ansi-escapes-3.2.0.tgz: Integrity check failed for "ansi-escapes" (computed integrity doesn't match our records, got "sha512-cBhpre4ma+U0T1oM5fXg7Dy1Jw7zzwv7lt/GoCpr+hDQJoYnKVPLL4dCvSEFMmQurOQvSrwT7SL/DAlhBI97RQ==")
    at SecurityError.ExtendableBuiltin (/opt/yarn-v1.15.2/lib/cli.js:721:66)
    at SecurityError.MessageError (/opt/yarn-v1.15.2/lib/cli.js:750:123)
    at new SecurityError (/opt/yarn-v1.15.2/lib/cli.js:779:113)
    at Extract.<anonymous> (/opt/yarn-v1.15.2/lib/cli.js:62700:25)
    at Extract.emit (events.js:201:15)
    at finishMaybe (/opt/yarn-v1.15.2/lib/cli.js:73383:14)
    at /opt/yarn-v1.15.2/lib/cli.js:73361:5
    at Extract.module.exports.Extract._final (/opt/yarn-v1.15.2/lib/cli.js:139683:3)
    at callFinal (/opt/yarn-v1.15.2/lib/cli.js:73354:10)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
error https://registry.yarnpkg.com/ansi-escapes/-/ansi-escapes-3.2.0.tgz: Integrity check failed for "ansi-escapes" (computed integrity doesn't match our records, got "sha512-cBhpre4ma+U0T1oM5fXg7Dy1Jw7zzwv7lt/GoCpr+hDQJoYnKVPLL4dCvSEFMmQurOQvSrwT7SL/DAlhBI97RQ==")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

These are my steps:
```
$ rm -rf ./.yarn
$ apk add yarn
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/6) Installing ca-certificates (20190108-r0)
(2/6) Installing c-ares (1.15.0-r0)
(3/6) Installing http-parser (2.8.1-r0)
(4/6) Installing libuv (1.23.2-r0)
(5/6) Installing nodejs (10.14.2-r0)
(6/6) Installing yarn (1.12.3-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 36 MiB in 22 packages
$ yarn cache clean
yarn cache v1.15.2
success Cleared cache.
Done in 0.05s.
$ yarn config set cache-folder .yarn
yarn config v1.15.2
success Set "cache-folder" to ".yarn".
Done in 0.05s.
$ yarn install --verbose
yarn install v1.15.2
```

**Comment by sindresorhus** [comment]
That must be a problem with Yarn and not this package and should be reported on the Yarn issue tracker.
